### ISSUE TITLE
question about websocket

### ISSUE THREAD

**Issue by kevindevm** [G33kDude/WebSocket.ahk#2]
so i use this for a trade site for a game, and all work out but i only can have 6 websocket open when i try to open other one i get this 
![image](https://user-images.githubusercontent.com/7692819/56619708-d7e84c00-65fc-11e9-8dc8-f327ff4738a1.png)
basically it say error line 1 character 1 code 0 no url and if i want to continue it will not open the socket, any chance about why this happen? thanks for this

**Comment by ilikebuttons** [comment]
Hi, I'm getting the same error when I change the URL to my Node.js running on a local host. The orignal URL provided("wss://echo.websocket.org/") does work though.

![AHK_WS_ERROR](https://user-images.githubusercontent.com/34816579/68106223-891e4780-fea6-11e9-9a41-a70d46205355.png)

**Comment by NickSeagull** [comment]
If it still matters, after debugging for a while, it appears like all kinds of URLs that do not start with `wss`, `ws` or `https` will fail.

It is a restriction of internet explorer (which is what this uses underneath) _[source](https://stackoverflow.com/questions/36667587/syntax-error-on-new-websocket-in-edge-internet-explorer)_

**Comment by miro-ux** [comment]
> Hi, I'm getting the same error when I change the URL to my Node.js running on a local host. The orignal URL provided("wss://echo.websocket.org/") does work though.
> 
> ![AHK_WS_ERROR](https://user-images.githubusercontent.com/34816579/68106223-891e4780-fea6-11e9-9a41-a70d46205355.png)

I was getting the same error using local websockets with PHP and Ratchet and I was able to fix this by removing the trailing slash at the end of the URL and using LAN IP instead of localhost.

`new Example("ws://192.168.1.10:8080/chat")`

**Comment by forbbs** [comment]
Yes,It is IE's limit.
old version has poor performance.
new version can't work on Win7.
hard question.
